Switch to Gatsby for better theme/features
closeio/engineering.close.com pull request #24
Opened 2020-09-23 21:25 UTC by craigmdennis

# Motivation
To move to a more product centric 'behind the scenes' approach to sharing content. Think "Inside Intercom" but for Close.

## To Do
- [ ]  Resolve conflicts
- [ ] Add Personal Access Token to Settings as a Secret called `GATSBY_PUBLISH_ACCESS_TOKEN` in order to push to the repo. Will need a repo admin to do this.

## What this PR does
- Uses Gatsby instead of Jekyll
- Uses a more design friendly theme
- Builds using GitHub Actions and deploy to the gh-pages branch
- Is ready for integrating with a headless CMS
- FIles are still markdown and still use frontmatter as previous

## Things to consider:
- Images are located in `/static/assets/uploads` in case we use Netlify CMS
- Pagination is not included
- Tags have been added to the 

---

The reason for _not_ using Netlify CMS is the way they preview content and use images. The images are uploadded and added to the markdown frontmatter with absolute paths. Gatsby image requires relative paths. There are some plugins but none seemed to work correctly. 

Alternatives are:
- https://www.netlifycms.org/docs/netlify-large-media/ (would be useful if we use Netlify for hosting)
- https://www.netlifycms.org/docs/cloudinary/
- https://www.netlifycms.org/docs/uploadcare/

2020-09-24 00:38 UTC, philfreo reviewed
Great stuff, thanks for moving this forward so far! Quick comments before I'm OOO:

- Your token link is broken, but can we use a Deploy Key instead of a user-specific one? (https://docs.github.com/en/developers/overview/managing-deploy-keys#deploy-keys)
  - Alternatively, if we want Vercel anyway for branch previews, then we might as well deploy this fully to Vercel (instead of GitHub Pages), and in that case then I don't think you need any GitHub token at all. Bart can help you get that setup since he already has a token for Vercel+GH. I've made both of you admins of this repo now too.
- Are we sure we don't want to keep post-specific folders for images (even if they all get moved inside `/static/assets/uploads` to keep track of which post-specific images go where?)

2020-09-24 00:38 UTC, philfreo commented on _data/posts/2013-05-02-sweating-the-ui-ux-details-in-close-emails.md
> +tags: [engineering]
Not sure exactly what all tags we want, but this one is more `product` than `engineering` focused.

2020-09-24 00:38 UTC, philfreo commented on src/pages/404.js
> +import React from 'react';
delete `src/images/icon.png` (file above this one)

2020-09-24 11:23 UTC, craigmdennis commented on _data/posts/2013-05-02-sweating-the-ui-ux-details-in-close-emails.md
> +tags: [engineering]
Good catch. Tags will have their own pages. And we might call out specific tags some global navigation somewhere. I'll change this one now.

2020-09-24 11:25 UTC, craigmdennis commented
> Are we sure we don't want to keep post-specific folders for images (even if they all get moved inside /static/assets/uploads to keep track of which post-specific images go where?)

This is an artefact of using a 'media library' while experimenting with Netlify CMS. I'll revert back to folders in the mean time for easier linking.

2020-09-28 13:33 UTC, philfreo commented
What's the branch preview password? I tried `branchpreviewsareverynice` (like we use on closeio) but that didn't work.

2020-09-28 13:34 UTC, craigmdennis commented
It's in the 1Password vault: `deathly-lime-fennel-aura`

2020-09-28 13:39 UTC, philfreo requested changes
Looking really good – Thanks for all this, really excited about it! Just a few comments.

2020-09-28 13:39 UTC, philfreo commented on README.md
> +## Developing the site
We should still include a Docker-based set of instructions for people that don't want to mess with node versions etc on their local machine. However that can come later after this is merged.

2020-09-28 13:39 UTC, philfreo commented on _includes/footer.html
> -  </script>
We should keep this analytics tracking script on the new site. Can you add that?

2020-09-28 13:39 UTC, philfreo commented on _posts/2020-02-03-redirects-using-cloudfront-lambda-edge/index.md
> +const REDIRECTS_DATA_REGION = 'us-east-1'
Here and elsewhere: We shouldn't be stripping semicolons from our JavaScript examples

2020-09-28 13:39 UTC, philfreo commented on _posts/2020-02-03-redirects-using-cloudfront-lambda-edge/index.md
> +      <ReplaceKeyWith />
I'm not sure if this new change is correct or not but I'd say don't change it unless you're sure it is.

2020-09-28 13:39 UTC, philfreo commented on src/components/navigation.js
> +const Navigation = () => (
Remove this if it's not used yet?

2020-09-28 13:39 UTC, philfreo commented on src/pages/404.js
> +          <Link to="/">home</Link> safely
```suggestion
          This page does not exist. Head to our <Link to="/">home page</Link> or let us know if something seems wrong.
```

2020-09-28 13:39 UTC, philfreo commented on .eslintrc.json
> +    "dagreD3": true,
It's good that you tried to follow the same as our closeio repo, but some of this definitely doesn't belong (and will ultimately be cleaned up from the UI repo too). @lukasmlady Can you suggest a clean eslintrc that matches what we'd want for a new repo?

(Also related to my semicolon comment below)

2020-09-28 13:42 UTC, philfreo commented
Rather than changing how `engineering.close.com` works by pointing it to Vercel etc., I'm thinking it may just be easier to set this up from the beginning at `making.close.com`. Then we can change `engineering.close.com` to point to a redirect (S3 bucket probably) like we do for other deprecated domains.

So I think I'm suggesting that you change all references of `engineering.close.com` to `making.close.com` here already before merge.

2020-09-28 13:47 UTC, craigmdennis commented on _posts/2020-02-03-redirects-using-cloudfront-lambda-edge/index.md
> +const REDIRECTS_DATA_REGION = 'us-east-1'
This is an Eslint thing that's been doing it automatically even though it's set to _add_ them in actual code. I'll try and fix (or at least revert these files; which is what I was doing).

2020-09-28 13:58 UTC, craigmdennis commented on _posts/2020-02-03-redirects-using-cloudfront-lambda-edge/index.md
> +      <ReplaceKeyWith />
Again, I think this is an eslint/prettier markdown codeblock thing. Will revert.

2020-09-28 16:08 UTC, buzinas commented on _posts/2020-02-03-redirects-using-cloudfront-lambda-edge/index.md
> +      <ReplaceKeyWith />
This is good, you shouldn't revert :)

2020-09-28 19:28 UTC, philfreo commented on _posts/2020-02-03-redirects-using-cloudfront-lambda-edge/index.md
> +const REDIRECTS_DATA_REGION = 'us-east-1'
Yeah I figured. Let's figure out why so it stops happening.

2020-09-28 19:31 UTC, philfreo commented on _posts/2020-02-03-redirects-using-cloudfront-lambda-edge/index.md
> +      <ReplaceKeyWith />
@buzinas You are 100% sure that AWS implementation of XML for S3 Redirection Rules likes this format? If not, then we shouldn't change this.

2020-09-29 13:54 UTC, craigmdennis commented on src/pages/404.js
> +          <Link to="/">home</Link> safely
Done. Removed the SVG and inline styles.

2020-09-29 13:54 UTC, craigmdennis commented on src/components/navigation.js
> +const Navigation = () => (
Done.

2020-09-29 13:54 UTC, craigmdennis commented on _posts/2020-02-03-redirects-using-cloudfront-lambda-edge/index.md
> +      <ReplaceKeyWith />
Reverted anyway.

2020-09-29 13:55 UTC, craigmdennis commented on _posts/2020-02-03-redirects-using-cloudfront-lambda-edge/index.md
> +const REDIRECTS_DATA_REGION = 'us-east-1'
Seems to have stopped now. Reverted some of the files. Some of them have applied JSX formatting.

2020-09-29 13:55 UTC, craigmdennis commented on _includes/footer.html
> -  </script>
Added this using the Segment gatsby plugin.

2020-09-29 13:56 UTC, craigmdennis commented on README.md
> +## Developing the site
Added in issue to tackle this separately https://github.com/closeio/engineering.close.com/issues/27

2020-09-30 15:04 UTC, merged